### PR TITLE
Use valid HTML

### PR DESCRIPTION
**Pull request by gabebw**
http://stackoverflow.com/questions/3493405/do-i-really-need-to-encode-as-amp

### CODE REVIEW

**Comment by gabebw** [comment]
You may also want to change the "base branch" for this repo to be `gh-pages` for future PR-makers.

**Comment by gfontenot** [comment]
what is this some kind of professional web site

**Comment by gfontenot** [comment]
> ooohhh look at me I'm all fancy with my html entities
>  -- this web site after I begrudgingly merge this hoity-toity PR

**Comment by gfontenot** [comment]
what you've turned this website into

**Pull request merged**
